mureader/views/ajax.py
from flask import Blueprint, jsonify, request
from flask_jwt_extended import current_user, get_jwt_identity

from mureader import models
from mureader.main import app, db, jwt_required

ajax_blueprint = Blueprint('ajax', __name__)

@ajax_blueprint.route('/like', methods=['POST'])
@jwt_required
def like():
    entry_id = request.form['entry_id']
    user_entry = models.UserEntry.query.filter_by(user=current_user, entry_id=entry_id).first()
    liked = bool(int(request.form['value']))
    if not user_entry:
        if liked: # you could like an entry that is not in your feed (if you see it in somebody else's feed)
            user_entry = models.UserEntry(user=current_user, entry_id=entry_id)
        else: # unliking a missing item should simply be ignored
            return jsonify(ok=True)
    user_entry.liked = liked
    db.session.add(user_entry)
    db.session.commit()
    return jsonify(ok=True)

@ajax_blueprint.route('/delete', methods=['POST'])
@jwt_required
def delete():
    entry_id = request.form['entry_id']
    if bool(int(request.form['value'])):
        models.UserEntry.query.filter_by(user=current_user, entry_id=entry_id).delete()
    else:
        db.session.add(models.UserEntry(user=current_user, entry_id=entry_id))
    db.session.commit()
    return jsonify(ok=True)

@ajax_blueprint.route('/follow', methods=['POST'])
@jwt_required
def follow():
    feed_id = request.form['feed_id']
    affect_news = bool(int(request.form['affect_news']))
    if not bool(int(request.form['value'])):
        models.Subscription.query.filter_by(user=current_user, feed_id=feed_id).delete()
        if affect_news:
            for ue in models.UserEntry.query \
                .join(models.Entry) \
                .filter(models.UserEntry.user==current_user, models.UserEntry.liked==False, models.Entry.feed_id==feed_id):
                db.session.delete(ue)
    else:
        db.session.add(models.Subscription(user=current_user, feed_id=feed_id))
        if affect_news:
            existing_entry_ids = {ue.entry_id for ue in models.UserEntry.query.join(models.Entry).filter(models.UserEntry.user==current_user, models.Entry.feed_id==feed_id)}
            for entry in models.Feed.query.filter_by(id=feed_id).first().entries:
                if entry.id not in existing_entry_ids:
                    db.session.add(models.UserEntry(user=current_user, entry=entry))
    db.session.commit()
    return jsonify(ok=True)

mureader/views/feed.py
from bs4 import BeautifulSoup
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_jwt_extended import current_user, get_jwt_identity, verify_jwt_in_request
from flask_jwt_extended.exceptions import NoAuthorizationError
import requests

from mureader import forms, models
from mureader.main import db, jwt_required

feed_blueprint = Blueprint('feed', __name__)

@feed_blueprint.route('/news', methods=['GET'])
def news():
    try:
        verify_jwt_in_request()
    except NoAuthorizationError:
        pass
    if current_user:
        entries = models.UserEntry.query \
            .join(models.Entry) \
            .filter(models.UserEntry.user==current_user, models.UserEntry.liked==False)
    else:
        entries = models.Entry.query
    entries = entries.order_by(models.Entry.updated_at.desc()).limit(100)

    return render_template('news.html', entries=entries, user=current_user)

@feed_blueprint.route('/liked', methods=['GET'])
@jwt_required
def liked():
    entries = models.UserEntry.query \
        .join(models.Entry) \
        .filter(models.UserEntry.user==current_user, models.UserEntry.liked==True) \
        .order_by(models.Entry.updated_at.desc())
    return render_template('news.html', entries=entries, user=current_user)

@feed_blueprint.route('/subscriptions', methods=['GET'])
@jwt_required
def subscriptions():
    subscribed_feed_ids = {s.feed_id for s in models.Subscription.query.filter_by(user=current_user)}
    feeds = [f for f in models.Feed.query.all()]
    for f in feeds:
        if f.id in subscribed_feed_ids:
            f.subscribed = True
    return render_template('subscriptions.html',
        feeds=feeds, user=current_user,
        form=forms.FollowWebsiteForm(), jwt_csrf_token=request.cookies.get('csrf_access_token'))

@feed_blueprint.route('/follow-website', methods=['POST'])
@jwt_required
def follow_website():
    if not current_user.is_pro:
        flash("Only pro users can follow external websites")
        return redirect(url_for('feed.subscriptions'))

    url = request.form['url']
    if not '://' in url:
        url = 'http://' + url
    while url.endswith('/'):
        url = url[:-1]

    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    links = soup.find_all('link', rel='alternate')
    links = [(l.attrs['href'], l.attrs['title'])
        for l in links
        if l.attrs['type'] in ['application/atom+xml', 'application/rss+xml']]
    links = [(url + u if u.startswith('/') else u, title) for u, title in links]
    if not links: # NOTE: here we just assumed that "no links" means this is a feed on itself
        # TODO: validate feed
        feed = models.Feed(url=request.form['url'])
        db.session.add(feed)
        db.session.commit()
        subscription = models.Subscription(user_id=current_user.id, feed_id=feed.id)
        db.session.add(subscription)
        db.session.commit()
        return redirect(url_for('feed.subscriptions'))
    else:
        form = forms.FollowFeedForm()
        form.url.choices = links
        return render_template('follow.html',
            user=current_user,
            form=form, jwt_csrf_token=request.cookies.get('csrf_access_token'))

mureader/views/user.py
from io import BytesIO

from flask import abort, Blueprint, flash, redirect, render_template, request, url_for
from flask_mail import Message
from flask_jwt_extended import create_access_token, create_refresh_token, current_user, set_access_cookies, set_refresh_cookies, unset_jwt_cookies
from flask_jwt_extended import get_jwt_identity, jwt_refresh_token_required
from itsdangerous import URLSafeTimedSerializer
import pyqrcode
from sqlalchemy.exc import IntegrityError

from mureader import forms, models
from mureader.main import app, db, mail, jwt_required

user_blueprint = Blueprint('user', __name__)

def send_confirmation_email(email):
    token = generate_confirmation_token(email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    try:
        subject = "Please confirm your email address"
        html = render_template('user/confirm-email-message.html', confirm_url=confirm_url)
        m = Message(subject, recipients=[email], html=html, sender=app.config['MAIL_DEFAULT_SENDER'])
        mail.send(m)
    except Exception as e:
        app.log_exception(e)
        app.logger.info('Confirmation url: %s', confirm_url)
        return "Failed to send confirmation email"

def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    return serializer.dumps(email)

def check_token(token, expiration=(60 * 10)):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    return serializer.loads(token, max_age=expiration)

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user:
        return redirect(url_for('feed.news'))

    if request.method == 'GET':
        return render_template('user/register.html', form=forms.EmailForm())

    error = None
    email = request.form['email']
    if not email:
        error = "Email is required"
    elif models.User.query.filter_by(email=email).first():
        error = "Email is already in use"
    if error is None:
        try:
            db.session.add(models.User(email))
            db.session.commit()
        except Exception as e:
            app.log_exception(e)
            error = "Failed to create user"

        error = send_confirmation_email(email)

    if error is None:
        return render_template('user/register.html', success=True)
    else:
        flash(error)
        return redirect(url_for('user.register'))

@user_blueprint.route('/confirm-email', defaults={'token': None}, methods=['GET', 'POST'])
@user_blueprint.route('/confirm-email/<token>', methods=['GET', 'POST'])
def confirm_email(token):
    if token is None:
        if request.method == 'GET':
            return render_template('user/confirm-email.html', form=forms.EmailForm())
        else:
            user = models.User.query.filter_by(email=request.form['email']).first()
            if not user:
                # don't need to say the user was not found
                app.logger.warn("Trying to confirm email for an inexisting user: %s", request.form['email'])
                return render_template('user/register.html', success=True)
            else:
                error = send_confirmation_email(user.email)
                if error:
                    flash(error)
                    return redirect(url_for('user.confirm_email'))
                else:
                    return render_template('user/register.html', success=True)

    try:
        email = check_token(token)
    except Exception:
        flash("The confirmation link is invalid or has expired")
        return redirect(url_for('user.register'))

    user = models.User.query.filter_by(email=email).first_or_404()
    if not user.email_confirmed:
        user.email_confirmed = True
        flash("Your email address was confirmed")
    if request.method == 'POST':
        user.set_password(request.form['new_password'])
        flash("Your password was changed")
    db.session.add(user)
    db.session.commit()

    url = pyqrcode.create(user.get_totp_uri())
    stream = BytesIO()
    url.svg(stream, scale=5, xmldecl=False, svgns=False, module_color="#802929")
    qr = stream.getvalue().decode('utf-8')

    return render_template('user/new-password.html', qr=qr, user=user, form=forms.NewPasswordForm())

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user:
        return redirect(url_for('feed.news'))

    if request.method == 'GET':
        return render_template('user/login.html', form=forms.LoginForm())

    email_or_username = request.form['email_or_username']
    token_or_password = request.form['token_or_password']
    user = models.User.query.filter_by(email=email_or_username).first()
    if not user:
        user = models.User.query.filter_by(username=email_or_username).first()
    login_success = False
    if not user:
        app.logger.info("User not found: %s", email_or_username)
    else:
        if user.verify_totp(token_or_password):
            app.logger.info("Login success token: %s", email_or_username)
            login_success = True
        if user.verify_password(token_or_password):
            app.logger.info("Login success password: %s", email_or_username)
            login_success = True

    if login_success:
        response = redirect(url_for('feed.news'))
        set_access_cookies(response, create_access_token(identity=user.email))
        set_refresh_cookies(response, create_refresh_token(identity=user.email))
        return response
    else:
        flash("Incorrect email or password or one-time token")
        return redirect(url_for('user.login'))

@user_blueprint.route('/me', methods=['GET', 'POST'])
@jwt_required
def me():
    if request.method == 'GET':
        return render_template('user/me.html', user=current_user,
            form=forms.ProfileForm(obj=current_user), jwt_csrf_token=request.cookies.get('csrf_access_token'))

    form = forms.ProfileForm(request.form, obj=current_user)
    if form.validate():
        form.populate_obj(current_user)
        db.session.add(current_user)
    try:
        db.session.commit()
    except IntegrityError:
        flash("The username you want is already in use")
        return redirect(url_for('user.me'))
    return render_template('user/me.html', user=current_user,
        form=forms.ProfileForm(obj=current_user), jwt_csrf_token=request.cookies.get('csrf_access_token'))

@user_blueprint.route('/logout', methods=['GET'])
def logout():
    response = redirect(url_for('feed.news'))
    unset_jwt_cookies(response)
    return response

@user_blueprint.route('/refresh-jwt', methods=['GET'])
@jwt_refresh_token_required
def refresh_jwt():
    response = redirect(url_for('feed.news'))
    set_access_cookies(response, create_access_token(identity=get_jwt_identity()))
    return response

mureader/templates/about.html
{% extends "base.html" %}
{% block content %}
<p>mureader is a simple reader that stays out your way. something like "google reader meets hacker news". you can use it to follow blogs that publish rss / atom feeds.</p>
<p>simple design that stays out your way, inspired by <a href="http://news.ycombinator.com" target="_blank">hacker news</a> and <a href="http://pinboard.in" target="_blank">pinboard</a></p>
{% endblock %}

mureader/templates/base.html
<html>
    <head>
        <style type="text/css">
            .entry-liked-1.entry-deleted-0 { background-color: #D3DFC1; }
            .entry-deleted-1 { background-color: #DAB2BA; }
            #navbar { background-color: #C4E38A; }
            .error { background-color: #DAB2BA; }
            .entry-liked-1 .like-link { display: none; }
            .entry-liked-0 .like-link { display: inline; }
            .entry-liked-1 .unlike-link { display: inline; }
            .entry-liked-0 .unlike-link { display: none; }
            .entry-deleted-1 .delete-link { display: none; }
            .entry-deleted-0 .delete-link { display: inline; }
            .entry-deleted-1 .undelete-link { display: inline; }
            .entry-deleted-0 .undelete-link { display: none; }
            .feed-followed-1 .follow-link { display: none; }
            .feed-followed-0 .follow-link { display: inline; }
            .feed-followed-1 .unfollow-link { display: inline; }
            .feed-followed-0 .unfollow-link { display: none; }
        </style>
        <script type="text/javascript">
        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2) {
                return parts.pop().split(';').shift();
            }
        }
        function replaceClass(eId, cOld, cNew) {
            var e = document.getElementById(eId);
            if (e.classList.contains(cOld)) {
                e.classList.remove(cOld);
            }
            e.classList.add(cNew);
        }
        function doPost(url, data, csrf_token, successCB) {
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function() {
                if (xhr.readyState == 4 && xhr.status == 200)
                {
                    var resp = JSON.parse(xhr.responseText);
                    if (resp.ok) {
                        successCB();
                    }
                }
            }
            xhr.open('POST', url);
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            var token = getCookie('csrf_access_token');
            xhr.send(`${data}&csrf_token=${csrf_token}&jwt_csrf_token=${token}`);
            return false;
        }
        function likeEntry(entry_id, value, csrf_token) {
            doPost("{{ url_for('ajax.like') }}", `entry_id=${entry_id}&value=${value}`, csrf_token,
                function() {
                    replaceClass(`entry-${entry_id}`, `entry-liked-${1-value}`, `entry-liked-${value}`);
                    if (value) {
                        replaceClass(`entry-${entry_id}`, `entry-deleted-1`, `entry-deleted-0`);
                    }
                }
            );
        }
        function deleteEntry(entry_id, value, csrf_token) {
            doPost("{{ url_for('ajax.delete') }}", `entry_id=${entry_id}&value=${value}`, csrf_token,
                function() {
                    replaceClass(`entry-${entry_id}`, `entry-deleted-${1-value}`, `entry-deleted-${value}`);
                }
            );
        }
        function followFeed(feed_id, value, csrf_token) {
            var affect_news = confirm(value ? "Do you want to also import old entries into your news feed?" : "Do you want to also delete existing entries from your news feed (liked entries will not be deleted)?") ? 1 : 0;
            doPost("{{ url_for('ajax.follow') }}", `feed_id=${feed_id}&value=${value}&affect_news=${affect_news}`, csrf_token,
                function() {
                    replaceClass(`feed-${feed_id}`, `feed-followed-${1-value}`, `feed-followed-${value}`);
                }
            );
        }
        </script>
    </head>
    <body>
    <center>
    <table width="85%">
        <tr id="navbar">
            <td>
                <table width="100%">
                    <tr>
                    <td width="5%"><a href="/">mureader</a></td>
                    <td>
                        {% if user %}
                            <a href="{{ url_for('feed.news') }}">news</a> |
                            <a href="{{ url_for('feed.liked') }}">liked</a> |
                            <a href="{{ url_for('feed.subscriptions') }}">subscriptions</a>
                        {% endif %}
                    </td>
                    <td style="text-align: right;">
                        {% if user %}
                            <a href="{{ url_for('user.me') }}">{{ user.display_name }}</a> |
                            <a href="{{ url_for('user.logout') }}">log out</a>
                        {% else %}
                            <a href="{{ url_for('user.login') }}">log in</a>
                        {% endif %}
                    </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr id="flashes">
            <td>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <table width="100%">
                {% for message in messages %}
                    <tr class="error"><td style="text-align: center;">{{ message }}</td></tr>
                {% endfor %}
            </table>
            {% endif %}
            {% endwith %}
            </td>
        </tr>
        <tr class="content">
            <td>
            {% block content %}{% endblock %}
            </td>
        </tr>
    </table>
    <hr />
    <a href="{{ url_for('main.about') }}">about</a>
    </center>
    </body>
</html>