usocial/controllers/account.py
import pytz

from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_jwt_extended import create_access_token, create_refresh_token, current_user, get_jwt_identity, set_access_cookies, set_refresh_cookies, unset_jwt_cookies, verify_jwt_in_request
from flask_jwt_extended.exceptions import NoAuthorizationError
from sqlalchemy.exc import IntegrityError

from usocial import forms, models as m, payments
from usocial.main import app, db, jwt_required

import config

account_blueprint = Blueprint('account', __name__)

def login_success(user):
    response = redirect(url_for('feed.items', liked=False))
    set_access_cookies(response, create_access_token(identity=user.username))
    set_refresh_cookies(response, create_refresh_token(identity=user.username))
    return response

def only_default_user():
    if m.User.query.count() == 1:
        return m.User.query.filter_by(username=m.User.DEFAULT_USERNAME).one_or_none()

def login_default_user():
    default_user = only_default_user()
    if default_user and not default_user.password:
        return login_success(default_user)

@account_blueprint.route('/', methods=['GET'])
def index():
    try:
        verify_jwt_in_request()
        return redirect(url_for('feed.items', liked=False))
    except NoAuthorizationError:
        return login_default_user() or redirect(url_for('account.login'))

@account_blueprint.route('/account', methods=['GET'])
@jwt_required
def account():
    q = db.session.query(m.UserItem).filter_by(user_id=current_user.id)
    sum_q = q.statement.with_only_columns([
        db.func.coalesce(db.func.sum(m.UserItem.stream_value_played), 0),
        db.func.coalesce(db.func.sum(m.UserItem.stream_value_paid), 0)])
    played_value, paid_value = q.session.execute(sum_q).one()
    paid_value_amounts = m.Action.get_total_amounts(current_user)

    return render_template('account.html', user=current_user,
        played_value=played_value, paid_value=paid_value, paid_value_amounts=paid_value_amounts,
        only_default_user=only_default_user(),
        version=config.VERSION, build=config.BUILD,
        lnd_info=payments.get_lnd_info())

@account_blueprint.route('/account/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if current_user:
            return redirect(url_for('feed.items', liked=False))
        else:
            return login_default_user() or render_template('login.html', user=None, skip_username=bool(only_default_user()), form=forms.LoginForm())

    username = request.form['username'] if not only_default_user() else m.User.DEFAULT_USERNAME
    password = request.form['password']
    user = m.User.query.filter_by(username=username).first()
    success = False
    if not user:
        app.logger.info("User not found: %s", username)
    else:
        if not user.password and not password:
            app.logger.info("Login success no auth: %s", username)
            success = True
        if user.verify_password(password):
            app.logger.info("Login success password: %s", username)
            success = True
    if success:
        return login_success(user)
    else:
        flash("Incorrect credentials.")
        return redirect(url_for('account.login'))

@account_blueprint.route('/account/password', methods=['GET', 'POST'])
@jwt_required
def password():
    if request.method == 'GET':
        return render_template('password.html', user=current_user,
            form=forms.NewPasswordForm(),
            jwt_csrf_token=request.cookies.get('csrf_access_token'))
    else:
        if request.form['new_password'] != request.form['repeat_new_password']:
            flash("Passwords don't match")
            return redirect(url_for('account.password'))
        current_user.set_password(request.form['new_password'])
        flash("Your password was changed")
        db.session.add(current_user)
        db.session.commit()
        return redirect(url_for('account.account'))

@account_blueprint.route('/account/logout', methods=['GET'])
def logout():
    response = redirect(url_for('account.login'))
    unset_jwt_cookies(response)
    return response

@account_blueprint.route('/account/volume', methods=['POST'])
@jwt_required
def update_volume():
    current_user.audio_volume = float(request.form['value'])
    db.session.add(current_user)
    db.session.commit()
    return jsonify(ok=True)

@account_blueprint.route('/account/timezone', methods=['POST'])
@jwt_required
def update_timezone():
    try:
        current_user.timezone = pytz.timezone(request.form['value']).zone
    except pytz.exceptions.UnknownTimeZoneError:
        return "Invalid timezone.", 400
    db.session.add(current_user)
    db.session.commit()
    return jsonify(ok=True)

usocial/controllers/feed.py
from datetime import datetime
import json

from babel.dates import format_timedelta
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_jwt_extended import current_user
import requests
from sqlalchemy import func
from urllib.parse import urlparse

from feedparsley import extract_feed_links, parse_feed

from usocial import forms, models as m, payments
from usocial.main import app, db, get_podcastindex, jwt_required

import config

feed_blueprint = Blueprint('feed', __name__)

def get_items_feeds(feed_id, item_q):
    def item_to_dict(i):
        return {
            'user_item': i[0], 'url': i[1], 'title': i[2], 'feed_id': i[3], 'updated_at': i[4],
            'enclosure_url': i[5], 'enclosure_type': i[6]}
    items = m.UserItem.query \
            .join(m.Item) \
            .add_columns(m.Item.url, m.Item.title, m.Item.feed_id, m.Item.updated_at, m.Item.enclosure_url, m.Item.enclosure_type) \
            .filter(m.UserItem.user == current_user) \
            .filter(item_q) \
            .order_by(m.Item.updated_at.desc())
    try:
        feed_id = int(feed_id)
        items = items.filter(m.Item.feed_id == feed_id)
    except ValueError:
        if feed_id == 'playing':
            items = items.filter(m.UserItem.play_position != 0)
    feeds = []
    for feed in m.Feed.query \
        .join(m.FeedGroup).join(m.Group) \
        .filter(m.Group.user == current_user) \
        .order_by(db.func.lower(m.Feed.title)) \
        .all():

        feeds.append({
            'id': feed.id,
            'title': feed.title,
            'is_podcast': feed.is_podcast,
            'url': feed.url,
            'fetched_at': current_user.localize(feed.fetched_at),
            'fetch_failed': feed.fetch_failed,
            'subscribed': 1,
            'active': feed_id == feed.id,
        })
    counts = {f_id: c for f_id, c in db.session.query(m.Feed.id, db.func.count(m.UserItem.item_id)) \
        .select_from(m.Feed).join(m.Item).join(m.UserItem) \
        .filter(m.UserItem.user == current_user) \
        .filter(item_q) \
        .group_by(m.Feed.id).all()}
    counts['total'] = sum(counts.values())
    return map(item_to_dict, items), feeds, counts

@feed_blueprint.route('/feeds/all/items', methods=['GET'], defaults={'feed_id': 'all', 'liked': False})
@feed_blueprint.route('/feeds/playing/items', methods=['GET'], defaults={'feed_id': 'playing', 'liked': False})
@feed_blueprint.route('/feeds/<int:feed_id>/items', methods=['GET'], defaults={'liked': False})
@feed_blueprint.route('/feeds/all/items/liked', methods=['GET'], defaults={'feed_id': 'all', 'liked': True})
@feed_blueprint.route('/feeds/playing/items/liked', methods=['GET'], defaults={'feed_id': 'playing', 'liked': True})
@feed_blueprint.route('/feeds/<int:feed_id>/items/liked', methods=['GET'], defaults={'liked': True})
@jwt_required
def items(liked, feed_id):
    user_item_filter = m.UserItem.liked == True if liked else m.UserItem.read == False
    items, feeds, counts = get_items_feeds(feed_id, user_item_filter)

    feed = None
    played_value, paid_value, paid_value_amounts, actions = 0, 0, [], []
    if feed_id == 'all':
        show_player = any(f['is_podcast'] for f in feeds)
    elif feed_id == 'playing':
        show_player = True
    else:
        feed = m.Feed.query.get_or_404(feed_id)
        show_player = feed.is_podcast
        q = db.session.query(m.UserItem) \
            .filter(m.UserItem.user_id == current_user.id, m.UserItem.item_id == m.Item.id, m.Item.feed_id == feed_id)
        sum_q = q.statement.with_only_columns([
            db.func.coalesce(db.func.sum(m.UserItem.stream_value_played), 0),
            db.func.coalesce(db.func.sum(m.UserItem.stream_value_paid), 0)])
        played_value, paid_value = q.session.execute(sum_q).one()
        paid_value_amounts = m.Action.get_total_amounts(current_user, feed_id)
        actions = m.Action.query.filter_by(user_id=current_user.id, feed_id=feed_id).order_by(m.Action.date)

    return render_template('items.html', liked=liked, user=current_user,
        feeds=feeds, items=items, counts=counts,
        feed=feed, show_player=show_player,
        played_value=played_value, paid_value=paid_value, paid_value_amounts=paid_value_amounts, actions=actions)

@feed_blueprint.route('/feeds/<int:feed_id>/follow', methods=['POST'])
@jwt_required
def follow(feed_id):
    if not bool(int(request.form['value'])): # unfollow
        for fg in m.FeedGroup.query \
            .join(m.Group) \
            .filter(m.Group.user == current_user, m.FeedGroup.feed_id == feed_id):
            db.session.delete(fg)
        for ue in m.UserItem.query \
            .join(m.Item) \
            .filter(m.UserItem.user == current_user, m.UserItem.liked == False, m.Item.feed_id == feed_id):
            db.session.delete(ue)
    else:
        group = m.Group.query.filter(m.Group.user == current_user, m.Group.name == m.Group.DEFAULT_GROUP).one_or_none()
        if not group:
            group = m.Group(user=current_user, name=m.Group.DEFAULT_GROUP)
            db.session.add(group)
            db.session.commit()
        db.session.add(m.FeedGroup(group=group, feed_id=feed_id))
        existing_item_ids = {ue.item_id for ue in m.UserItem.query.join(m.Item).filter(m.UserItem.user == current_user, m.Item.feed_id == feed_id)}
        for item in m.Feed.query.filter_by(id=feed_id).first().items:
            if item.id not in existing_item_ids:
                db.session.add(m.UserItem(user=current_user, item=item))
    db.session.commit()
    return jsonify(ok=True)

@feed_blueprint.route('/feeds/websites/add', methods=['GET', 'POST'])
@jwt_required
def add_website():
    if request.method == 'GET':
        return render_template('add_website.html', user=current_user,
            form=forms.FollowWebsiteForm(), jwt_csrf_token=request.cookies.get('csrf_access_token'))

    url = request.form['url']
    if not '://' in url:
        url = f"http://{url}"
    while url.endswith('/'):
        url = url[:-1]

    r = requests.get(url)
    alt_links = extract_feed_links(url, r.text)
    if not alt_links: # NOTE: here we just assumed that "no links" means this is a feed on itself
        feed_url = request.form['url']
        parsed_feed = parse_feed(feed_url)
        if not parsed_feed:
            flash(f"Cannot parse feed at: {feed_url}")
            return redirect(url_for('feed.add_website'))
        feed = db.session.query(m.Feed).filter_by(url=feed_url).one_or_none()
        if not feed:
            feed = m.Feed(url=feed_url)
            db.session.add(feed)
        feed.update(parsed_feed)
        db.session.commit()
        new_items, updated_items = feed.update_items(parsed_feed)
        db.session.commit()
        group = m.Group.query.filter(m.Group.user == current_user, m.Group.name == m.Group.DEFAULT_GROUP).one_or_none()
        if not group:
            group = m.Group(user=current_user, name=m.Group.DEFAULT_GROUP)
            db.session.add(group)
            db.session.commit()
        db.session.add(m.FeedGroup(group=group, feed_id=feed.id))
        db.session.commit()
        existing_item_ids = {ue.item_id for ue in m.UserItem.query.join(m.Item).filter(m.UserItem.user == current_user, m.Item.feed_id == feed.id)}
        for item in feed.items:
            if item.id not in existing_item_ids:
                db.session.add(m.UserItem(user=current_user, item=item))
        db.session.commit()
        return redirect(url_for('feed.items', liked=False))
    else:
        form = forms.FollowFeedForm()
        form.url.choices = alt_links
        return render_template('add_website.html',
            user=current_user,
            form=form, jwt_csrf_token=request.cookies.get('csrf_access_token'))

@feed_blueprint.route('/feeds/podcasts/search', methods=['GET', 'POST'])
@jwt_required
def search_podcasts():
    if request.method == 'GET':
        return render_template('search_podcasts.html', user=current_user,
            form=forms.SearchPodcastForm(), jwt_csrf_token=request.cookies.get('csrf_access_token'))

    q = m.Feed.query.join(m.FeedGroup).join(m.Group).filter(m.Group.user == current_user).all()
    subscribed_urls = {f.url for f in q}
    result = get_podcastindex().search(request.form['keywords'])
    feeds = [{'id': f['id'],
              'url': f['url'],
              'title': f['title'],
              'domain': urlparse(f['link']).netloc,
              'homepage_url': f['link'],
              'description': f['description'],
              'image': f['artwork'],
              'categories': [c for c in (f['categories'] or {}).values()],
              'subscribed': f['url'] in subscribed_urls}
             for f in result['feeds']]
    return render_template('search_podcasts.html',
        user=current_user,
        podcastindex_feeds=feeds,
        form=forms.SearchPodcastForm(), jwt_csrf_token=request.cookies.get('csrf_access_token'))

@feed_blueprint.route('/feeds/podcasts/follow', methods=['POST'])
@jwt_required
def follow_podcast():
    feed_url = request.form['url']
    feed = db.session.query(m.Feed).filter_by(url=feed_url).one_or_none()
    if not feed:
        feed = m.Feed(
            url=request.form['url'],
            homepage_url=request.form['homepage_url'],
            title=request.form['title'])
        db.session.add(feed)
    parsed_feed = parse_feed(feed.url)
    if not parsed_feed:
        return jsonify(ok=False)
    feed_from_index = get_podcastindex().podcastByFeedUrl(feed_url)
    value_from_index = feed_from_index.get('feed', {}).get('value') if feed_from_index else None
    feed.update(parsed_feed)
    feed.update_value_spec(parsed_feed['value_spec'], parsed_feed['value_recipients'], value_from_index)
    db.session.commit()
    new_items, updated_items = feed.update_items(parsed_feed)
    db.session.commit()
    group = m.Group.query.filter(m.Group.user == current_user, m.Group.name == m.Group.DEFAULT_GROUP).one_or_none()

usocial/templates/account.html
{% extends "base.html" %}
{% block content %}
<h2>Karma</h2>
<h3>Podcast value</h3>
<table>
<tr><td>Total played</td><td>{{ played_value }} minutes</td></tr>
{% for action_name, amount in paid_value_amounts %}
<tr><td>Total {{ action_name }}</td><td>{{ amount }} sats</td></tr>
{% endfor %}
</table>

<h2>Account</h2>
<table>
    <tr><td><strong title="username">{{ user.username }}</strong> {% if user.password %}<i title="password protected" class="fas fa-key"></i>{% else %}<i title="no password" class="fas fa-unlock"></i>{% endif %}</td><td><a href="{{ url_for('account.password') }}">set password</a></td></tr>
    <tr><td>API key</td><td>{{ user.fever_api_key }}</td></tr>
    {% if not (only_default_user and not user.password) %}
    <tr><td><a href="{{ url_for('account.logout') }}">log out</a></td></tr>
    {% endif %}
</table>

<h2>App</h2>
<table>
    <tr><td>Version</td><td>{{ version }}</td></tr>
    <tr><td>Build</td><td>{{ build }}</td></tr>
    <tr><td>Website</td><td><a href="http://usocial.me" target="_blank">usocial.me</a></td></tr>
    <tr><td>LND</td><td>{% if lnd_info %}connected to node <small>{{ lnd_info.identity_pubkey }}</small>{% else %}not connected{% endif %}</td></tr>
</table>
{% endblock %}

usocial/templates/add_website.html
{% extends "base.html" %}
{% block content %}
<div>
    <form action="{{ url_for('feed.add_website') }}" method="POST">
        <input id="jwt_csrf_token" name="jwt_csrf_token" type="hidden" value="{{ jwt_csrf_token }}" />
        {{ form.hidden_tag() }}
        {{ form.url.label }}
        {{ form.url }}
        <button type="submit">Go!</button>
    </form>
</div>
{% endblock %}

usocial/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>{% if feed %}{{ feed.title }} :: {% endif %}usocial :: the anti-social network</title>
        <link rel="icon" href="/static/favicon.ico" sizes="any"><!-- 32×32 -->
        <link rel="icon" href="/static/mu.svg" type="image/svg+xml">
        <link rel="stylesheet" href="/static/fontawesome/all.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') | autoversion }}" />
        <script type="text/javascript" src="{{ url_for('static', filename='utils.js') | autoversion }}"></script>
        <script>
            var csrfToken = '{{ csrf_token() }}'; // {# https://github.com/wtforms/flask-wtf/blob/main/src/flask_wtf/csrf.py #}
            var username = '{% if user %}{{ user.username }}{% endif %}';
            var userTimezone = '{% if user and user.timezone %}{{ user.timezone }}{% endif %}';
        </script>
    </head>
    <body onload="onBodyLoad();">
    <center>
    <table width="85%">
        <tr id="navbar">
            <td>
                <table width="100%">
                    <tr>
                    <td>
                        {% if user %}
                            <a href="{{ url_for('feed.items', liked=False) }}"><i title="my feeds" class="fas fa-rss"></i></a> |
                            <a href="{{ url_for('feed.items', liked=True) }}"><i title="my liked items" class="fas fa-heart"></i></a>
                        {% else %}
                            Welcome to <strong>usocial</strong>. Please log in to continue.
                        {% endif %}
                    </td>
                    <td style="text-align: right;">
                        {% if user %}
                            <a href="{{ url_for('account.account') }}"><i title="account" class="fas fa-user-cog"></i></a>
                        {% endif %}
                    </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td id="flashes">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <table width="100%">
                {% for message in messages %}
                    <tr class="error"><td style="text-align: center;">{{ message }}</td></tr>
                {% endfor %}
            </table>
            {% endif %}
            {% endwith %}
            </td>
        </tr>
        <tr class="content">
            <td>
            {% block content %}{% endblock %}
            </td>
        </tr>
    </table>
    </center>
    </body>
</html>

usocial/templates/items.html
{% extends "base.html" %}
{% block content %}

{% if not liked %}
  <a href="{{ url_for('feed.add_website') }}" title="add blog">+ <i class="fas fa-blog"></i></a> <a href="{{ url_for('feed.search_podcasts') }}" title="add podcast">+ <i class="fas fa-podcast"></i></a>
{% endif %}

{% set feed_value_spec = feed.value_spec %}

<hr />
<table class="split-panels">
<tr><td class="left-panel">
<table class="feeds-table">
    <tr class="main-row feed-row">
        <td class="feed-actions"></td>
        <td id="feed-all"
            onclick="feedClick(event, 'all', {% if liked %}true{% else %}false{% endif %}); return false;">
            All
        </td>
        <td></td>
        <td>{{ counts['total'] }}</td>
    </tr>
    <tr class="main-row feed-row">
        <td class="feed-actions"></td>
        <td id="feed-playing"
            onclick="feedClick(event, 'playing', {% if liked %}true{% else %}false{% endif %}); return false;">
            Playing
        </td>
        <td></td>
        <td></td>
    </tr>
    {% for feed in feeds %}
    {% if counts[feed.id] %}
        <tr class="main-row feed-row {% if feed.active %}feed-active {% endif %}"
            onclick="feedClick(event, {{ feed.id }}, {% if liked %}true{% else %}false{% endif %}); return false;"
            title="{% if feed.fetched_at %}fetched at {{ feed.fetched_at.strftime('%-d %b %-H:%M') }}{% endif %}">
            <td id="feed-{{ feed.id }}" class="feed-actions feed-followed-1">
                <span class="unfollow-link">
                    <span onclick="followFeed({{ feed.id }}, 0); return false;" href=""><i title="unfollow" class="far fa-eye"></i></span>
                </span>
                <span class="follow-link">
                    <span onclick="followFeed({{ feed.id }}, 1); return false;" href=""><i title="follow" class="far fa-eye-slash"></i></span>
                </span>
            </td>
            <td id="feed-{{ feed.id }}">
                {{ feed.title }} {% if feed.is_podcast %}<i class="fas fa-podcast"></i>{% else %}<i class="fas fa-blog"></i>{% endif %}
            </td>
            <td>
                {% if feed.fetch_failed %}<i class="fas fa-exclamation" title="fetch failed"></i>{% endif %}
            </td>
            <td>{{ counts[feed.id] }}</td>
        </tr>
        <tr><td></td></tr>
    {% endif %}
    {% endfor %}
</table>
</td><td class="right-panel">

{% if feed %}
<h2 id="feed-title">{{ feed.title }}</h2>
<table id="feed-details">
    {% if feed_value_spec and feed_value_spec.is_supported %}
    <tr>
        <td>
            suggested
        </td>
        <td>
            <span id="value-spec-amount">{{ feed_value_spec.sats_amount }}</span> sats / minute
        </td>
    </tr>
    <tr>
        <td>
            streamed
        </td>
        <td>
            <span id="stream-value-played">{{ played_value }}</span>
            <span id="stream-value-paid" style="display: none;">{{ paid_value }}</span> minutes
            <a href="" title="contribute" onclick="showStreamPayment(); return false;"><i class="fas fa-bolt"></i>
        </td>
    </tr>
    <tr id="stream-payment" style="display: none">
        <td></td>
        <td>
            <input id="stream-value-amount" type="number" size="4" min="100" step="100" /> sats
            <button id="send-stream-value" onclick="sendStreamValue({{ feed.id }});">Send</button>
        </td>
    </tr>
    <tr id="boost-payment" style="display: none">
        <td></td>
        <td>
            <input id="boost-value-amount" type="number" size="4" min="100" value="100" step="50" /> sats
            <button id="send-boost-value" onclick="sendBoostValue();">Boost!</button>
        </td>
    </tr>
    <tr>
        <td>contributed</td>
        <td>
            <a href="" title="show history" onclick="showActions(); return false;"><i class="fas fa-history"></i></a>
            {% for action_name, amount in paid_value_amounts %}
                {{ action_name }} <span id="contribution-amount-{{ action_name }}">{{ amount }}</span> sats
            {% endfor %}
        </td>
    </tr>
    {% for action in actions %}
        <tr class="actionRow" style="display: none">
            <td></td>
            <td>
                <small>{{ action.date.strftime('%-d %b %Y %-H:%M') }}</small> {% if action.errors %}<i class="fas fa-exclamation" title="has errors"></i>{% endif %} {{ action.action.value }} {{ action.amount_msat // 1000 }} sats
            </td>
        </tr>
    {% endfor %}
    {% endif %}
</table>
{% endif %}

{% if show_player %}
<table class="fullWidthTable">
<tr><td>
<audio id="podcastPlayer" controls="controls" onvolumechange="podcastPlayerVolumeChanged();" data-volume="{{ user.audio_volume }}">
    <source id="audioSource" src="" type=""></source>
    Your browser does not support the audio tag.
</audio>
</td></tr>
</table>
{% endif %}

<table id="items" class="items-table">
    {% for i in items %}
        <tr id="item-{{ i.user_item.item_id }}"
            class="main-row item-row item item-liked-{% if i.user_item.liked %}1{% else %}0{% endif %} item-hidden-{% if i.user_item.read %}1{% else %}0{% endif %}"
            onclick="itemClick(event, {{ i.feed_id }}, {{ i.user_item.item_id }}); return false;"
            data-id="{{ i.user_item.item_id }}"
            data-feed_id="{{ i.feed_id }}"
            data-enclosure_url="{{ i.enclosure_url or '' }}"
            data-enclosure_type="{{ i.enclosure_type or '' }}"
            data-play_position="{{ i.user_item.play_position }}"
            {% if feed_value_spec and feed_value_spec.is_supported %}data-has_value_spec="1"{% endif %}>
            <td>
                <span class="unlike-link">
                    <span onclick="likeItem({{ i.feed_id }}, {{ i.user_item.item_id }}, 0); return false;" href=""><i title="unlike" class="fas fa-heart" style="font-weight: solid;"></i></span>
                </span>
                <span class="like-link">
                    <span onclick="likeItem({{ i.feed_id }}, {{ i.user_item.item_id }}, 1); return false;" href=""><i title="like" class="far fa-heart" style="font-weight: regular;"></i></span>
                </span>
                {% if not liked %}
                <span class="unhide-link">
                    <span onclick="hideItem({{ i.feed_id }}, {{ i.user_item.item_id }}, 0); return false;" href=""><i title="undelete" class="fas fa-trash-alt"></i></span>
                </span>
                <span class="hide-link">
                    <span onclick="hideItem({{ i.feed_id }}, {{ i.user_item.item_id }}, 1); return false;" href=""><i title="delete" class="far fa-trash-alt"></i></span>
                </span>
                {% endif %}
                <span class="open-link">
                    <span href="" onclick="window.open('{{ i.url }}', '_blank'); return false;"><i title="open" class="fas fa-external-link-square-alt"></i></span>
                </span>
                {{ i.title }}
            </td>
            {% if i.updated_at %}
            <td title="{{ i.updated_at.strftime('%-d %b %Y %-H:%M') }}"><nobr>{{ i.updated_at.strftime('%-d %b') }}</nobr></td>
            {% else %}
            <td></td>
            {% endif %}
        </tr>
        <tr><td></td></tr>
    {% endfor %}
</table>
</td>
</tr>
</table>
{% endblock %}

usocial/templates/login.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        <table class="fullWidthTable" style="padding-top: 10%;">
        {% if not skip_username %}
        <tr class="form-row">
            <td>{{ form.username.label }}</td>
            <td>{{ form.username }}</td>
        </tr>
        {% endif %}
        <tr class="form-row">
            <td>{{ form.password.label }}</td>
            <td>{{ form.password }}</td>
        </tr>
        <tr class="form-row">
            <td></td>
            <td><button type="submit">Log in</button></td>
        </tr>
        </table>
    </form>
{% endblock %}

usocial/templates/password.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    <input id="jwt_csrf_token" name="jwt_csrf_token" type="hidden" value="{{ jwt_csrf_token }}" />
    {{ form.hidden_tag() }}
    <table class="fullWidthTable" style="padding-top: 10%;">
        <tr><td></td><td>Note: Leave empty to remove the password!</td></tr>
        <tr class="form-row">
            <td>{{ form.new_password.label }}</td>
            <td>{{ form.new_password }}</td>
        </tr>
        <tr class="form-row">
            <td>{{ form.repeat_new_password.label }}</td>
            <td>{{ form.repeat_new_password }}</td>
        </tr>
        <tr class="form-row">
            <td></td>
            <td><button type="submit" onclick="if(document.getElementById('new_password').value === '') { return confirm('Are you sure you want to remove the password?'); } ">Set!</button></td>
        </tr>
    </table>
</form>
{% endblock %}

usocial/templates/search_podcasts.html
{% extends "base.html" %}
{% block content %}
<div>
    <form action="{{ url_for('feed.search_podcasts') }}" method="POST">
        <input id="jwt_csrf_token" name="jwt_csrf_token" type="hidden" value="{{ jwt_csrf_token }}" />
        {{ form.hidden_tag() }}
        {{ form.keywords.label }}
        {{ form.keywords }}
        <button type="submit">Find!</button>
    </form>
</div>
<table>
    {% for feed in podcastindex_feeds %}
        <tr class="main-row">
            <td>
                <img src="{{ feed.image }}" width="100" height="100" />
            </td>
            <td id="podcast-{{ feed.id }}" class="feed-followed-{% if feed.subscribed %}1{% else %}0{% endif %}">
                {{ feed.title }} (<a target="_blank" href="{{ feed.homepage_url }}">{{ feed.domain }}</a>)
                <span class="unfollow-link">
                    <span onclick="unfollowPodcast({{ feed.id }}, '{{ feed.url }}'); return false;" href="#"><i class="far fa-eye"></i></span>
                </span>
                <span class="follow-link">
                    <span onclick="followPodcast({{ feed.id }}, '{{ feed.url }}', '{{ feed.homepage_url }}', '{{ feed.title }}'); return false;" href="#"><i class="far fa-eye-slash"></i></span>
                </span>
                <div class="extra-row">
                    {% for cat in feed.categories %}{{ cat }} {% endfor %}
                </div>
            </td>
        </tr>
        <tr><td></td></tr>
    {% endfor %}
</table>
{% endblock %}