musocial/views/feed.py
from datetime import datetime

from babel.dates import format_timedelta
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_jwt_extended import current_user
import requests
from sqlalchemy import func
from urllib.parse import urlparse

import podcastindex

from musocial import forms, models as m
from musocial.parser import extract_feed_links, parse_feed
from musocial.main import db, jwt_required

import config

feed_blueprint = Blueprint('feed', __name__)

def get_items_feeds(feed_id, q):
    items = m.UserItem.query \
            .join(m.Item) \
            .add_columns(m.Item.url, m.Item.title, m.Item.feed_id, m.Item.enclosure_url, m.Item.enclosure_type) \
            .filter(m.UserItem.user == current_user) \
            .filter(q)
    if feed_id:
        items = items.filter(m.Item.feed_id == feed_id)
    items = list(items) # TODO: optimize this by computing show_player differently
    feeds = []
    for feed in m.Feed.query \
        .join(m.FeedGroup).join(m.Group) \
        .filter(m.Group.user == current_user).all():
        feeds.append({
            'id': feed.id,
            'title': feed.title,
            'url': feed.url,
            'subscribed': 1,
            'active': feed_id == feed.id,
        })
    counts = {f_id: c for f_id, c in db.session.query(m.Feed.id, db.func.count(m.UserItem.item_id)) \
        .select_from(m.Feed).join(m.Item).join(m.UserItem) \
        .filter(m.UserItem.user == current_user) \
        .filter(q) \
        .group_by(m.Feed.id).all()}
    counts['total'] = sum(counts.values())
    return items, feeds, counts

@feed_blueprint.route('/feeds/all/items', methods=['GET'])
@feed_blueprint.route('/feeds/<int:feed_id>/items', methods=['GET'])
@jwt_required
def items(feed_id=None):
    items, feeds, counts = get_items_feeds(feed_id, m.UserItem.read == False)
    feed = m.Feed.query.filter_by(id=feed_id).one_or_none() if feed_id else None
    show_player = items and all(i[4] for i in items)
    return render_template('items.html', feeds=feeds, items=items, counts=counts, feed=feed, show_player=show_player, user=current_user)

@feed_blueprint.route('/feeds/all/items/liked', methods=['GET'])
@feed_blueprint.route('/feeds/<int:feed_id>/items/liked', methods=['GET'])
@jwt_required
def liked_items(feed_id=None):
    items, feeds, counts = get_items_feeds(feed_id, m.UserItem.liked == True)
    feed = m.Feed.query.filter_by(id=feed_id).one_or_none() if feed_id else None
    show_player = items and all(i[4] for i in items)
    return render_template('items.html', feeds=feeds, items=items, counts=counts, liked=True, feed=feed, show_player=show_player, user=current_user)

@feed_blueprint.route('/feeds/<int:feed_id>/follow', methods=['POST'])
@jwt_required
def follow(feed_id):
    if not bool(int(request.form['value'])): # unfollow
        for fg in m.FeedGroup.query \
            .join(m.Group) \
            .filter(m.Group.user == current_user, m.FeedGroup.feed_id == feed_id):
            db.session.delete(fg)
        for ue in m.UserItem.query \
            .join(m.Item) \
            .filter(m.UserItem.user == current_user, m.UserItem.liked == False, m.Item.feed_id == feed_id):
            db.session.delete(ue)
    else:
        group = m.Group.query.filter(m.Group.user == current_user, m.Group.name == m.Group.DEFAULT_GROUP).one_or_none()
        if not group:
            group = m.Group(user=current_user, name=m.Group.DEFAULT_GROUP)
            db.session.add(group)
            db.session.commit()
        db.session.add(m.FeedGroup(group=group, feed_id=feed_id))
        existing_item_ids = {ue.item_id for ue in m.UserItem.query.join(m.Item).filter(m.UserItem.user == current_user, m.Item.feed_id == feed_id)}
        for item in m.Feed.query.filter_by(id=feed_id).first().items:
            if item.id not in existing_item_ids:
                db.session.add(m.UserItem(user=current_user, item=item))
    db.session.commit()
    return jsonify(ok=True)

@feed_blueprint.route('/feeds/websites/add', methods=['GET', 'POST'])
@jwt_required
def add_website():
    if request.method == 'GET':
        return render_template('add_website.html', user=current_user,
            form=forms.FollowWebsiteForm(), jwt_csrf_token=request.cookies.get('csrf_access_token'))

    url = request.form['url']
    if not '://' in url:
        url = f"http://{url}"
    while url.endswith('/'):
        url = url[:-1]

    r = requests.get(url)
    alt_links = extract_feed_links(url, r.text)
    if not alt_links: # NOTE: here we just assumed that "no links" means this is a feed on itself
        feed_url = request.form['url']
        parsed_feed = parse_feed(feed_url)
        if not parsed_feed:
            flash(f"Cannot parse feed at: {feed_url}")
            return redirect(url_for('feed.add_website'))
        existing_feed = m.Feed.query.filter_by(url=feed_url).one_or_none()
        feed = existing_feed or m.Feed(url=feed_url)
        feed.update(parsed_feed)
        db.session.add(feed)
        db.session.commit()
        new_items, updated_items = feed.update_items(parsed_feed)
        db.session.add(feed)
        for item in new_items + updated_items:
            db.session.add(item)
        db.session.commit()
        group = m.Group.query.filter(m.Group.user == current_user, m.Group.name == m.Group.DEFAULT_GROUP).one_or_none()
        if not group:
            group = m.Group(user=current_user, name=m.Group.DEFAULT_GROUP)
            db.session.add(group)
            db.session.commit()
        db.session.add(m.FeedGroup(group=group, feed_id=feed.id))
        db.session.commit()
        existing_item_ids = {ue.item_id for ue in m.UserItem.query.join(m.Item).filter(m.UserItem.user == current_user, m.Item.feed_id == feed.id)}
        for item in feed.items:
            if item.id not in existing_item_ids:
                db.session.add(m.UserItem(user=current_user, item=item))
        db.session.commit()
        return redirect(url_for('feed.items'))
    else:
        form = forms.FollowFeedForm()
        form.url.choices = alt_links
        return render_template('add_website.html',
            user=current_user,
            form=form, jwt_csrf_token=request.cookies.get('csrf_access_token'))

@feed_blueprint.route('/feeds/podcasts/search', methods=['GET', 'POST'])
@jwt_required
def search_podcasts():
    if request.method == 'GET':
        return render_template('search_podcasts.html', user=current_user,
            form=forms.SearchPodcastForm(), jwt_csrf_token=request.cookies.get('csrf_access_token'))

    q = m.Feed.query.join(m.FeedGroup).join(m.Group).filter(m.Group.user == current_user, m.Group.name == m.Group.PODCASTS_GROUP).all()
    subscribed_urls = {f.url for f in q}
    index = podcastindex.init({'api_key': config.PODCASTINDEX_API_KEY, 'api_secret': config.PODCASTINDEX_API_SECRET})
    result = index.search(request.form['keywords'])
    feeds = [{'id': f['id'],
              'url': f['url'],
              'title': f['title'],
              'domain': urlparse(f['link']).netloc,
              'homepage_url': f['link'],
              'description': f['description'],
              'image': f['artwork'],
              'categories': [c for c in (f['categories'] or {}).values()],
              'subscribed': f['url'] in subscribed_urls}
             for f in result['feeds']]
    return render_template('search_podcasts.html',
        user=current_user,
        podcastindex_feeds=feeds,
        form=forms.SearchPodcastForm(), jwt_csrf_token=request.cookies.get('csrf_access_token'))

@feed_blueprint.route('/feeds/podcasts/follow', methods=['POST'])
@jwt_required
def follow_podcast():
    feed = m.Feed.query.filter_by(url=request.form['url']).one_or_none()
    if not feed:
        feed = m.Feed(
            url=request.form['url'],
            homepage_url=request.form['homepage_url'],
            title=request.form['title'])
        db.session.add(feed)
    parsed_feed = parse_feed(feed.url)
    if not parsed_feed:
        return jsonify(ok=False)
    feed.update(parsed_feed)
    db.session.add(feed)
    db.session.commit()
    new_items, updated_items = feed.update_items(parsed_feed)
    db.session.add(feed)
    for item in new_items + updated_items:
        db.session.add(item)
    db.session.commit()
    group = m.Group.query.filter(m.Group.user == current_user, m.Group.name == m.Group.PODCASTS_GROUP).one_or_none()
    if not group:
        group = m.Group(user=current_user, name=m.Group.PODCASTS_GROUP)
        db.session.add(group)
        db.session.commit()
    db.session.add(m.FeedGroup(group=group, feed_id=feed.id))
    db.session.commit()
    existing_item_ids = {ue.item_id for ue in m.UserItem.query.join(m.Item).filter(m.UserItem.user == current_user, m.Item.feed_id == feed.id)}
    for item in feed.items:
        if item.id not in existing_item_ids:
            db.session.add(m.UserItem(user=current_user, item=item))
    db.session.commit()
    return jsonify(ok=True)

@feed_blueprint.route('/feeds/podcasts/unfollow', methods=['POST'])
@jwt_required
def unfollow_podcast():
    feed = m.Feed.query.filter_by(url=request.form['url']).one_or_none()
    if feed:
        for fg in m.FeedGroup.query.join(m.Group).filter(m.Group.user == current_user, m.FeedGroup.feed == feed):
            db.session.delete(fg)
        db.session.commit()
        # TODO: delete items!
    return jsonify(ok=True)

def update_item(item_id, do):
    user_item = m.UserItem.query.filter_by(user=current_user, item_id=item_id).first()
    do(user_item)
    db.session.add(user_item)
    db.session.commit()
    return jsonify(ok=True)

@feed_blueprint.route('/feeds/<int:feed_id>/items/<int:item_id>/like', methods=['POST'])
@jwt_required
def like_item(feed_id, item_id):
    def update(ui):
        ui.liked = bool(int(request.form['value']))
    return update_item(item_id, update)

@feed_blueprint.route('/feeds/<int:feed_id>/items/<int:item_id>/hide', methods=['POST'])

musocial/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>musocial - the anti-social network</title>
        <link rel="stylesheet" href="/static/fontawesome/all.css">
        <link rel="stylesheet" href="/static/style.css" />
        <script type="text/javascript" src="/static/utils.js"></script>
    </head>
    <body>
    <center>
    <table width="85%">
        <tr id="navbar">
            <td>
                <table width="100%">
                    <tr>
                    <td>
                        {% if user %}
                            <a href="{{ url_for('feed.items') }}">feeds</a> |
                            <a href="{{ url_for('feed.liked_items') }}">liked</a>
                        {% endif %}
                    </td>
                    <td style="text-align: right;">
                        {% if user %}
                            <a href="{{ url_for('account.me') }}">{{ user.username }}</a>
                        {% else %}
                            <a href="{{ url_for('account.register') }}">register</a> |
                            <a href="{{ url_for('account.login') }}">log in</a>
                        {% endif %}
                    </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr id="flashes">
            <td>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <table width="100%">
                {% for message in messages %}
                    <tr class="error"><td style="text-align: center;">{{ message }}</td></tr>
                {% endfor %}
            </table>
            {% endif %}
            {% endwith %}
            </td>
        </tr>
        <tr class="content">
            <td>
            {% block content %}{% endblock %}
            <hr />
            </td>
        </tr>
    </table>
    </center>
    </body>
</html>

musocial/templates/follow_website.html
{% extends "base.html" %}
{% block content %}
<div>
    <form action="{{ url_for('feed.follow_website') }}" method="POST">
        <input id="jwt_csrf_token" name="jwt_csrf_token" type="hidden" value="{{ jwt_csrf_token }}" />
        {{ form.hidden_tag() }}
        {{ form.url.label }}
        {{ form.url }}
        <button type="submit">Go!</button>
    </form>
</div>
{% endblock %}

musocial/templates/podcast_search.html
{% extends "base.html" %}
{% block content %}
<div>
    <form action="{{ url_for('feed.podcast_search') }}" method="POST">
        <input id="jwt_csrf_token" name="jwt_csrf_token" type="hidden" value="{{ jwt_csrf_token }}" />
        {{ form.hidden_tag() }}
        {{ form.keywords.label }}
        {{ form.keywords }}
        <button type="submit">Find!</button>
    </form>
</div>
<table>
    {% for feed in podcastindex_feeds %}
        <tr class="main-row">
            <td>
                <img src="{{ feed.image }}" width="100" height="100" />
            </td>
            <td id="podcast-{{ feed.id }}" class="feed-followed-{% if feed.subscribed %}1{% else %}0{% endif %}">
                {{ feed.title }} (<a target="_blank" href="{{ feed.homepage_url }}">{{ feed.domain }}</a>)
                <span class="unfollow-link">
                    <span onclick="unfollowPodcast({{ feed.id }}, '{{ feed.url }}', '{{ csrf_token() }}'); return false;" href="#"><i class="far fa-eye"></i></span>
                </span>
                <span class="follow-link">
                    <span onclick="followPodcast({{ feed.id }}, '{{ feed.url }}', '{{ feed.homepage_url }}', '{{ feed.title }}', '{{ csrf_token() }}'); return false;" href="#"><i class="far fa-eye-slash"></i></span>
                </span>
                <div class="extra-row">
                    {% for cat in feed.categories %}{{ cat }} {% endfor %}
                </div>
            </td>
        </tr>
        <tr><td></td></tr>
    {% endfor %}
</table>
{% endblock %}

musocial/templates/subscriptions.html
{% extends "base.html" %}
{% block content %}
<table>
        {% for feed in feeds %}
            <tr><td id="feed-{{ feed.id }}" class="feed-followed-{% if feed.subscribed %}1{% else %}0{% endif %}">
                {{ feed.title }}
                <span class="unfollow-link">
                    (<a onclick="followFeed({{ feed.id }}, 0, '{{ csrf_token() }}'); return false;" href="">unfollow</a>)
                </span>
                <span class="follow-link">
                    (<a onclick="followFeed({{ feed.id }}, 1, '{{ csrf_token() }}'); return false;" href="">follow</a>)
                </span>
            </td></tr>
        {% endfor %}
</table>
<hr />
<div>
    <form action="{{ url_for('feed.follow_website') }}" method="POST">
        <input id="jwt_csrf_token" name="jwt_csrf_token" type="hidden" value="{{ jwt_csrf_token }}">
        {{ form.hidden_tag() }}
        {{ form.url.label }}
        {{ form.url }}
        <button type="submit">Follow website</button>
    </form>
</div>
{% endblock %}